# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.7"

before_install:
  - "nvm install 12"

install:
  - pip install poetry
  - poetry install
  - yarn

script:
  - poetry run py.test tests
