---
# definition of rulesets for advancing through the
# stages of a dribdat project

stages:
  -
    id: 0
    name: CHALLENGE
    phase: Challenge
    description: 🚧 This is an idea or challenge description
    conditions:
      validate:
        -
          field: summary
          min: 5
          help: Your challenge needs a short summary.
        -
          field: excerpt
          min: 123
          help: At least 123 characters in the challenge pitch.
      agree:
        - The challenge is well documented, with links to resources and contacts.
        - We accept this challenge as realistic in the time limits of the event.
  -
    id: 5
    name: NEW
    phase: Researching
    description: 👪 A team has formed and started a project
    conditions:
      validate:
        -
          field: team
          min: 1
          max: 5
          help: Between 1 and 5 members need to join your project.
        -
          field: contact_url
          test: validurl
          help: Provide a contact link in the Details of your project page.
      agree:
        - We have a shared channel or working area in which to collaborate.
        - Our team members will work together for the duration of the event.
  -
    id: 10
    name: RESEARCHED
    phase: Sketching
    description: ⚗️ Scoping research has been done and documented
    conditions:
      validate:
        -
          field: source_url
          test: validurl
          help: Provide a source link in your project Details.
      agree:
        - A source code repository or shared folder has been set up and shared.
        - We have defined the scope of the project, and have documented our goals.
  -
    id: 20
    name: SKETCHED
    phase: Prototyping
    description: 🎨 Initial designs have been sketched and shared
    conditions:
      validate:
        -
          field: image_url
          test: validurl
          help: Upload or link to an image in your project Details.
      agree:
        - Everyone on the team was able to contribute something to the design.
        - We used a wireframing tool, or just paper, to sketch and share our idea.
  -
    id: 30
    name: PROTOTYPED
    phase: Launching
    description: 🐣 A prototype of the idea has been developed
    conditions:
      validate:
        -
          field: webpage_url
          test: validurl
          help: Provide a project link to an online demo, embedded if possible.
      agree:
        - Contributions from outside of our team do not include any major functionality.
        - We own the rights, use open licenses, or have written permission for all data, assets and code included.
  -
    id: 40
    name: LAUNCHED
    phase: Promoting
    description: 🎈 The prototype has been deployed and presented
    conditions:
      validate:
        -
          field: autotext_url
          test: validurl
          help: Link and sync a remote repository or README for your project.
      agree:
        - Any third-party data, assets or software are correctly attributed.
        - We have thanked every team member and mentor.
  -
    id: 50
    name: LIVE
    phase: Supporting
    description: 🚀 This project is live and available to the public
    conditions:
      validate:
        -
          field: download_url
          test: validurl
          help: Provide a working download link in your project Details.
      agree:
        - The full results of our project can be obtained under an open license.
        - It is possible to contact the maintainers with questions or feedback.
