name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        name: [ macos, windows, ubuntu ]
        include:
          - name: macos
            os: macos-latest
            python-version: 3.7
          - name: windows
            os: windows-latest
            python-version: 3.8
          - name: ubuntu
            os: ubuntu-latest
            python-version: 3.9
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install
        run: |
          pip install poetry
          poetry install
          npx yarn
      - name: Run tests
        run: |
          poetry run pytest tests
